import os

EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_FROM = os.getenv("EMAIL_FROM")
PASSWORD = os.getenv("PASSWORD")
EMAIL_SEND_TO = os.getenv("EMAIL_SEND_TO")
PHONE = os.getenv("PHONE")

LINKEDIN_ACCOUNT_EMAIL = os.getenv("LINKEDIN_ACCOUNT_EMAIL")
LINKEDIN_ACCOUNT_PASSWORD = os.getenv("LINKEDIN_ACCOUNT_PASSWORD")
